export const FEATURED_PACKAGES = [
  {
    id: "1",
    title: "Kerala God's Own Country - Houseboat & Munnar",
    slug: "kerala-backwaters-munnar",
    destination: "Kerala",
    duration_days: 6,
    price_per_person: 18999,
    original_price: 24999,
    cover_image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&q=80",
    short_description: "Cruise through serene backwaters on a houseboat, explore misty tea gardens of Munnar and pristine beaches of Varkala.",
    rating: 4.9,
    reviews_count: 312,
    best_seller: true,
    featured: true,
    type: "domestic",
  },
  {
    id: "2",
    title: "Rajasthan Royal Heritage Circuit",
    slug: "rajasthan-royal-heritage",
    destination: "Rajasthan",
    duration_days: 8,
    price_per_person: 21999,
    original_price: 28999,
    cover_image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=600&q=80",
    short_description: "Explore majestic forts, vibrant bazaars and golden sand dunes of the royal state of Rajasthan.",
    rating: 4.8,
    reviews_count: 245,
    best_seller: false,
    featured: true,
    type: "domestic",
  },
  {
    id: "3",
    title: "Manali-Spiti Valley Expedition",
    slug: "manali-spiti-valley",
    destination: "Himachal Pradesh",
    duration_days: 7,
    price_per_person: 15999,
    original_price: 19999,
    cover_image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    short_description: "Journey through dramatic high-altitude landscapes, ancient Buddhist monasteries and pristine Himalayan valleys.",
    rating: 4.7,
    reviews_count: 189,
    best_seller: false,
    featured: true,
    type: "adventure",
  },
  {
    id: "4",
    title: "Bali Romance & Adventure Package",
    slug: "bali-romance-adventure",
    destination: "Bali, Indonesia",
    duration_days: 7,
    price_per_person: 52999,
    original_price: 64999,
    cover_image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&q=80",
    short_description: "Temples, rice terraces, volcanic peaks, world-class surfing and stunning sunset views in paradise.",
    rating: 4.9,
    reviews_count: 428,
    best_seller: true,
    featured: true,
    type: "international",
  },
  {
    id: "5",
    title: "Thailand Golden Triangle Explorer",
    slug: "thailand-golden-triangle",
    destination: "Thailand",
    duration_days: 8,
    price_per_person: 44999,
    original_price: 54999,
    cover_image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=600&q=80",
    short_description: "Bangkok temples, Chiang Mai elephants, and Phuket beaches in one incredible journey.",
    rating: 4.8,
    reviews_count: 367,
    best_seller: false,
    featured: true,
    type: "international",
  },
  {
    id: "6",
    title: "Andaman Islands - Beach & Snorkel",
    slug: "andaman-beach-snorkel",
    destination: "Andaman Islands",
    duration_days: 6,
    price_per_person: 24999,
    original_price: 29999,
    cover_image: "https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?w=600&q=80",
    short_description: "Crystal clear waters, pristine beaches, coral reefs and marine life in India's tropical paradise.",
    rating: 4.8,
    reviews_count: 198,
    best_seller: false,
    featured: false,
    type: "domestic",
  },
];

export const FIXED_DEPARTURES_DATA = [
  {
    id: "fd1",
    package_title: "Kashmir Great Lakes Trek",
    destination: "Kashmir",
    cover_image: "https://images.unsplash.com/photo-1566402441996-3e6a33b77b1f?w=600&q=80",
    departure_date: "2024-06-15",
    return_date: "2024-06-22",
    duration_days: 8,
    price_per_person: 28999,
    available_seats: 8,
    total_seats: 16,
    status: "limited",
    slug: "kashmir-great-lakes-trek",
  },
  {
    id: "fd2",
    package_title: "Char Dham Yatra 2024",
    destination: "Uttarakhand",
    cover_image: "https://images.unsplash.com/photo-1543832923-44667a44c804?w=600&q=80",
    departure_date: "2024-05-20",
    return_date: "2024-06-05",
    duration_days: 17,
    price_per_person: 35999,
    available_seats: 14,
    total_seats: 20,
    status: "available",
    slug: "char-dham-yatra-2024",
  },
  {
    id: "fd3",
    package_title: "Bali Group Departure",
    destination: "Bali, Indonesia",
    cover_image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&q=80",
    departure_date: "2024-07-10",
    return_date: "2024-07-17",
    duration_days: 8,
    price_per_person: 54999,
    available_seats: 4,
    total_seats: 20,
    status: "limited",
    slug: "bali-group-departure-july",
  },
  {
    id: "fd4",
    package_title: "Spiti Valley Jeep Expedition",
    destination: "Himachal Pradesh",
    cover_image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    departure_date: "2024-08-01",
    return_date: "2024-08-10",
    duration_days: 10,
    price_per_person: 22999,
    available_seats: 12,
    total_seats: 16,
    status: "available",
    slug: "spiti-valley-jeep-expedition",
  },
];

export const TESTIMONIALS_DATA = [
  {
    id: "1",
    name: "Priya Sharma",
    location: "Mumbai",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b6b38e9f?w=150&q=80",
    rating: 5,
    review: "Our Kerala honeymoon was absolutely magical! Travel Holiday took care of every detail — from the houseboat experience to the Munnar sunrise. The team was incredibly responsive and helpful throughout the trip.",
    destination: "Kerala",
    travel_date: "December 2023",
  },
  {
    id: "2",
    name: "Rajesh Kumar",
    location: "Delhi",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80",
    rating: 5,
    review: "The Rajasthan tour package was exceptional. We visited 6 cities in 8 days and the arrangements were seamless. Hotel quality was top-notch and our guide Ramesh was knowledgeable and fun!",
    destination: "Rajasthan",
    travel_date: "November 2023",
  },
  {
    id: "3",
    name: "Anita Patel",
    location: "Ahmedabad",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&q=80",
    rating: 5,
    review: "Bali with Travel Holiday was a dream come true! Every resort, every activity was perfectly planned. They even arranged a surprise anniversary dinner. Highly recommend for international tours!",
    destination: "Bali",
    travel_date: "January 2024",
  },
  {
    id: "4",
    name: "Suresh Menon",
    location: "Bangalore",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&q=80",
    rating: 4,
    review: "The Manali-Spiti trek was challenging and beautiful. Travel Holiday's support team was available 24/7 during the trip. Excellent arrangements considering the remote locations we visited.",
    destination: "Himachal Pradesh",
    travel_date: "August 2023",
  },
  {
    id: "5",
    name: "Deepika Nair",
    location: "Kochi",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&q=80",
    rating: 5,
    review: "Absolutely loved the Thailand package. Bangkok, Chiang Mai and Phuket — all covered perfectly. The accommodations were premium and food recommendations were spot on!",
    destination: "Thailand",
    travel_date: "February 2024",
  },
  {
    id: "6",
    name: "Arun Verma",
    location: "Pune",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&q=80",
    rating: 5,
    review: "Third trip booked through Travel Holiday and it keeps getting better! The Andaman package was phenomenal. Havelock Island snorkeling experience was once in a lifetime.",
    destination: "Andaman",
    travel_date: "March 2024",
  },
];

export const GALLERY_DATA = [
  {
    url: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&q=80",
    alt: "Kerala Backwaters",
    destination: "Kerala",
    cols: 2,
    rows: 1,
  },
  {
    url: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=600&q=80",
    alt: "Jaisalmer Fort",
    destination: "Rajasthan",
    cols: 1,
    rows: 1,
  },
  {
    url: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&q=80",
    alt: "Bali Temple",
    destination: "Bali",
    cols: 1,
    rows: 2,
  },
  {
    url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    alt: "Himalayan Peaks",
    destination: "Himachal Pradesh",
    cols: 1,
    rows: 1,
  },
  {
    url: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&q=80",
    alt: "Dubai Skyline",
    destination: "Dubai",
    cols: 1,
    rows: 1,
  },
  {
    url: "https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?w=600&q=80",
    alt: "Andaman Beach",
    destination: "Andaman",
    cols: 1,
    rows: 1,
  },
  {
    url: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=600&q=80",
    alt: "Thailand Temple",
    destination: "Thailand",
    cols: 1,
    rows: 1,
  },
  {
    url: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=600&q=80",
    alt: "Singapore Gardens",
    destination: "Singapore",
    cols: 1,
    rows: 1,
  },
];
